APP_NAME="mini-rag"
APP_VERSION="0.1.0"
OPENAI_API_KEY="your_openai_api_key_here"

FILE_ALLOWED_TYPES= ["text/plain" , "application/pdf"]
FILE_MAX_SIZE=10
FILE_DEFAULT_CHUNK_SIZE=512000

POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="mohamed29"
POSTGRES_HOST="localhost"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="minirag"


# ========================= LLM Config =========================
GENERATION_BACKEND = "OPENAI"
EMBEDDING_BACKEND="OPENAI"

OPENAI_API_KEY="ollama_api_key"
OPENAI_API_URL="http://172.31.128.1:11434/v1/"

GENERATION_MODEL_ID_LITERAL = ["gpt-4o-mini", "qwen3:8b"]
GENERATION_MODEL_ID="qwen3:8b"
EMBEDDING_MODEL_ID="bge-m3:latest"
EMBEDDING_MODEL_SIZE=1024

INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_TOKENS=1000
GENERATION_DEFAULT_TEMPERATURE=0.1
OPENAI_TIMEOUT=120.0

# ========================= Vector DB Config =========================
VECTOR_DB_BACKEND_LITERAL = ["QDRANT", "PGVECTOR"]
VECTOR_DB_BACKEND="PGVECTOR"
VECTOR_DB_PATH="qdrant_db"
VECTOR_DB_DISTANCE_METHOD="cosine"
VECTOR_DB_PGVEC_INDEX_THRESHOLD = 900

# ========================= Template Configs =========================
PRIMARY_LANG = "ar"
DEFAULT_LANG = "en"